#!/bin/sh

sxhkd &
ulauncher --hide-window --no-window-shadow &
nitrogen --restore &
fcitx5 &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &
[ -x ~/.cargo/bin/buzz ] && ~/.cargo/bin/buzz &
if [ -x ~/.cargo/bin/keybase-chat-notifier ]; then
	keybase chat api-listen | ~/.cargo/bin/keybase-chat-notifier &
fi
if [ -x /usr/bin/dropbox ]; then
    /usr/bin/dropbox &
fi

# psensor &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a ulauncher focus=on
bspc rule -a sxiv state=floating center=true
bspc rule -a polybar border=off manage=off

bspc rule -a Wine border=off

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# grep "grp:.*toggle" /usr/share/X11/xkb/rules/base.lst
sleep 2s && setxkbmap -option ctrl:nocaps

